controller_list:
  - name: fake_robot_arm_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - frame_one
      - frame_two
      - frame_three
initial:  # Define initial robot poses per group
  - group: robot_arm_hand
    pose: reach