arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - frame_one
    - frame_two
    - frame_three
  gains:
    frame_one:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    frame_two:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    frame_three:
      p: 100
      d: 1
      i: 1
      i_clamp: 1